version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:15
    container_name: supplychain_db
    environment:
      POSTGRES_DB: supplychain
      POSTGRES_USER: supplychain_user
      POSTGRES_PASSWORD: supplychain_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - supplychain_network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: supplychain_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - supplychain_network

  # Django Backend
  backend:
    build: ./backend
    container_name: supplychain_backend
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DEBUG=1
      - DATABASE_URL=postgresql://supplychain_user:supplychain_password@db:5432/supplychain
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
    networks:
      - supplychain_network

  # React Frontend (for later)
  frontend:
    build: ./frontend
    container_name: supplychain_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api
    depends_on:
      - backend
    networks:
      - supplychain_network

volumes:
  postgres_data:
  redis_data:

networks:
  supplychain_network:
    driver: bridge
