# Generated by Django 4.2.7 on 2025-09-04 00:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('widget_type', models.CharField(choices=[('CHART', 'Chart'), ('METRIC', 'Metric'), ('TABLE', 'Table'), ('KPI', 'KPI Card'), ('TIMELINE', 'Timeline')], max_length=20)),
                ('category', models.CharField(choices=[('INVENTORY', 'Inventory'), ('ORDERS', 'Orders'), ('FINANCE', 'Finance'), ('LOGISTICS', 'Logistics'), ('PERFORMANCE', 'Performance'), ('GENERAL', 'General')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('configuration', models.JSONField(help_text='Widget configuration and settings')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='KPIMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('metric_type', models.CharField(choices=[('COUNT', 'Count'), ('PERCENTAGE', 'Percentage'), ('CURRENCY', 'Currency'), ('DURATION', 'Duration'), ('RATIO', 'Ratio')], max_length=20)),
                ('category', models.CharField(choices=[('INVENTORY', 'Inventory'), ('ORDERS', 'Orders'), ('FINANCE', 'Finance'), ('LOGISTICS', 'Logistics'), ('CUSTOMER', 'Customer'), ('SUPPLIER', 'Supplier'), ('PERFORMANCE', 'Performance')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('calculation_logic', models.TextField(help_text='How the metric is calculated')),
                ('target_value', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('warning_threshold', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('critical_threshold', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('report_type', models.CharField(choices=[('INVENTORY', 'Inventory Report'), ('ORDER', 'Order Report'), ('FINANCIAL', 'Financial Report'), ('LOGISTICS', 'Logistics Report'), ('PERFORMANCE', 'Performance Report'), ('CUSTOMER', 'Customer Report'), ('SUPPLIER', 'Supplier Report')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('template_config', models.JSONField(help_text='Report template configuration')),
                ('parameters', models.JSONField(blank=True, help_text='Report parameters and filters')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['report_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly')], max_length=20)),
                ('recipients', models.JSONField(help_text='List of email recipients')),
                ('parameters', models.JSONField(blank=True, help_text='Report parameters')),
                ('is_active', models.BooleanField(default=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('report_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.reporttemplate')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DataExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('export_format', models.CharField(choices=[('CSV', 'CSV'), ('EXCEL', 'Excel'), ('JSON', 'JSON'), ('PDF', 'PDF')], max_length=20)),
                ('data_source', models.CharField(help_text='Data source for export', max_length=100)),
                ('filters', models.JSONField(blank=True, help_text='Export filters and parameters')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('file_path', models.CharField(blank=True, help_text='Path to exported file', max_length=500)),
                ('file_size', models.BigIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_x', models.IntegerField(default=0, help_text='X coordinate on dashboard')),
                ('position_y', models.IntegerField(default=0, help_text='Y coordinate on dashboard')),
                ('width', models.IntegerField(default=4, help_text='Widget width (1-12 grid)')),
                ('height', models.IntegerField(default=3, help_text='Widget height in rows')),
                ('is_visible', models.BooleanField(default=True)),
                ('custom_settings', models.JSONField(blank=True, help_text='User-specific widget settings')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('widget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.dashboardwidget')),
            ],
            options={
                'ordering': ['position_y', 'position_x'],
                'unique_together': {('user', 'widget')},
            },
        ),
        migrations.CreateModel(
            name='MetricValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=4, max_digits=15)),
                ('date', models.DateField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, help_text='Additional context for the metric value')),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='analytics.kpimetric')),
            ],
            options={
                'ordering': ['-date', '-timestamp'],
                'unique_together': {('metric', 'date')},
            },
        ),
    ]
