# Generated by Django 4.2.7 on 2025-09-04 00:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_license', models.CharField(max_length=50, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('ON_DELIVERY', 'On Delivery'), ('OFF_DUTY', 'Off Duty'), ('SUSPENDED', 'Suspended')], default='AVAILABLE', max_length=20)),
                ('experience_years', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=50, unique=True)),
                ('vehicle_type', models.CharField(choices=[('TRUCK', 'Delivery Truck'), ('VAN', 'Delivery Van'), ('CAR', 'Car'), ('MOTORCYCLE', 'Motorcycle')], max_length=20)),
                ('license_plate', models.CharField(max_length=20, unique=True)),
                ('capacity', models.IntegerField(help_text='Capacity in cubic feet')),
                ('fuel_efficiency', models.DecimalField(decimal_places=2, help_text='MPG', max_digits=5)),
                ('current_status', models.CharField(choices=[('AVAILABLE', 'Available'), ('IN_USE', 'In Use'), ('MAINTENANCE', 'Under Maintenance'), ('OUT_OF_SERVICE', 'Out of Service')], default='AVAILABLE', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('home_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse')),
            ],
            options={
                'ordering': ['vehicle_number'],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_number', models.CharField(max_length=50, unique=True)),
                ('planned_start_time', models.DateTimeField()),
                ('planned_end_time', models.DateTimeField()),
                ('actual_start_time', models.DateTimeField(blank=True, null=True)),
                ('actual_end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PLANNED', max_length=20)),
                ('total_distance', models.DecimalField(decimal_places=2, help_text='Distance in miles', max_digits=8)),
                ('estimated_fuel_cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.driver')),
                ('end_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_routes', to='inventory.warehouse')),
                ('start_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_routes', to='inventory.warehouse')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.vehicle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField(help_text='Stop sequence number')),
                ('estimated_arrival', models.DateTimeField()),
                ('actual_arrival', models.DateTimeField(blank=True, null=True)),
                ('estimated_departure', models.DateTimeField()),
                ('actual_departure', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='logistics.route')),
            ],
            options={
                'ordering': ['route', 'sequence'],
                'unique_together': {('route', 'sequence')},
            },
        ),
    ]
